version: "3"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
    volumes:
      - ./config:/config
      - ./shows:/data/tvshows # Volume for shows library
      - ./movies:/data/movies # Volume for movies library
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: always