version: '3'
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - 25565:25565
    restart: always
    volumes:
      - ./data:/data
    environment:
      - EULA=TRUE
      - SEED=TRUE
      - ONLINE_MODE=FALSE
      - DIFFICULTY=easy
      - VERSION=1.19